name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ./branch
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ./main
          ref: refs/heads/main


      - name: Run Docker1
        uses: ./branch/action-a
        with:
          MY_NAME: "Mona"

