name: A workflow for my Hello World file
on: [pull_request]
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    if: context.payload.pull_request.user.login == 'parthea' && context.payload.pull_request.title == 'test'
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}
          path: ./branch

      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: ./main
          ref: refs/heads/main

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install pandas
        run: pip3 install pandas

      # - name: Run change_summary.py
      #   run: python3 ./branch/change_summary.py

      - name: Update PR Body
        uses: actions/github-script@v2.0.0
        with:
          script: |
            const newBody = `test`
            github.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: newBody
            })
