name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}
          path: ./branch

      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: ./main
          ref: refs/heads/main

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install pandas
        run: pip install pandas

      - name: Run Docker1
        uses: ./branch/action-a
        with:
          MY_NAME: "Mona"

